Update data-cassandra sample with more test cases
Native tests will still fail till datastax/java-driver#1612 is resolved, still causing java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Compressor.